### ISSUE TITLE
Control Panel Switch - Control Panel doesnt show up again.

### ISSUE THREAD

**Issue by tomsaath** [unsoluble/smalltime#42] opened 2021-06-03 05:19 UTC
Hello, its me again.
When i hide the Smalltime control panel, i cant show it up again by clicking the button. I have to restart the world. Then the button reacts and the control panel appears again.

Tested in:
- System: Das Schwarze Auge/The Dark Eye (5th Edition)
- Foundry Version 0.7.10 and 0.8.6

**Comment by unsoluble** [comment] 2021-06-03 05:55
Hmm. So DSA doesn't run under 0.8.6 yet, and I can't reproduce this behaviour under 0.7.10. Does it still do this for you with no other modules enabled?

**Comment by tomsaath** [comment] 2021-06-03 06:17
I run the unofficial releaser version... but i thougt this also happend to me in 0.7.9... i will try further tests an write the outcome here.

**Comment by yoshisman8** [comment] 2021-06-04 19:31
Can repo this issue, Clicking the button to show the panel after it's been hidden makes it not show up. Additionally the panel just doesn't show up for players at all.

**Comment by unsoluble** [comment] 2021-06-04 20:59
@yoshisman8 What Foundry and game system versions?

**Comment by unsoluble** [comment] 2021-06-11 18:38
Can't repro this, and haven't received any further info; closing for now.

**Closed by unsoluble** 2021-06-11 18:38 UTC
