### ISSUE TITLE
Breaking Player Configuration

### ISSUE THREAD

**Issue by aruguy** [unsoluble/smalltime#44] opened 2021-06-05 22:03 UTC
I've narrowed it down to this module:
With SmallTime enabled, whenever I click on the 'Configure Players' button under 'Game Settings', I get an error and I'm returned to the /join page instead of /players.

**Comment by unsoluble** [comment] 2021-06-05 23:09
Weird! Can you screenshot the error for me? What Foundry and SmallTime versions?

**Comment by unsoluble** [comment] 2021-06-11 18:38
Can't reproduce, no further info provided; closing for now.

**Closed by unsoluble** 2021-06-11 18:38 UTC
